default: 
  adapter: postgresql
  pool: 5
  timeout: 5000

development: 
  adapter: postgresql
  database: rewindhiphop1
  pool: 5
  timeout: 5000

production: 
  adapter: postgresql
  database: rewindhiphop1
  pool: 5
  timeout: 5000

test: 
  adapter: postgresql
  database: rewindhiphop1
  pool: 5
  timeout: 5000

